[profile.default]
solc_version = "0.8.26+commit.8a97fa7a"
src = "src"
out = "out"
extra_output_files = ["metadata"]
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
